name: update-stats
concurrency: 'update-stats'

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo:
          - idaholab/advcubit
          - idaholab/atDisco
          - idaholab/blackbear
          - idaholab/civet
          - idaholab/civet_example_recipes
          - idaholab/CMIP
          - idaholab/Code_Generator
          - idaholab/conda-moose
          - idaholab/Deep-Lynx
          - idaholab/Deep-Lynx-Python-Package
          - idaholab/DIAMOND
          - idaholab/EMRALD
          - idaholab/EMV
          - idaholab/falcon
          - idaholab/FieLDS
          - idaholab/Gauss_Algorithms
          - idaholab/GranularFlowModels
          - idaholab/HERON
          - idaholab/homebrew-moose
          - idaholab/HPC_Job_Tracker
          - idaholab/hpcswtest
          - idaholab/HYBRID
          - idaholab/hyrax
          - idaholab/ICSNPP
          - idaholab/labrat
          - idaholab/large_media
          - idaholab/LIGGGHTS-INL
          - idaholab/Location-Generalizer
          - idaholab/LOGOS
          - idaholab/magpie
          - idaholab/Malcolm
          - idaholab/mastodon
          - idaholab/moose
          - idaholab/moosetools
          - idaholab/mytrim
          - idaholab/NRIC-DE
          - idaholab/package_builder
          - idaholab/pika
          - idaholab/presentations
          - idaholab/PRISM
          - idaholab/raven
          - idaholab/schematics
          - idaholab/SIEVAS
          - idaholab/SPEMMCRA
          - idaholab/SPPARKS
          - idaholab/SR2ML
          - idaholab/STAR
          - idaholab/STEM
          - idaholab/STIG
          - idaholab/stork
          - idaholab/STOTS
          - idaholab/TEAL
          - idaholab/TMAP8
          - idaholab/Topology_Generator
          - idaholab/VDEA
          - idaholab/virtual_test_bed
          - idaholab/WiiBin
          - idaholab/XFEMParaviewPlugin
          - IdahoLabResearch/CIACS
          - IdahoLabResearch/CoCuNi
          - IdahoLabResearch/DREEM
          - IdahoLabResearch/HEA_Code
          - IdahoLabResearch/LISA
          - IdahoLabResearch/MFSCO
          - IdahoLabResearch/TAPsolver
          - IdahoLabResearch/WOODCOM
          - IdahoLabCuttingBoard/ADREM
          - IdahoLabCuttingBoard/CLATesting
          - IdahoLabCuttingBoard/DAIRIEES
          - IdahoLabCuttingBoard/FakeADFS
          - IdahoLabCuttingBoard/Gauss_Algorithms_C
          - IdahoLabCuttingBoard/IGCAPT
          - IdahoLabCuttingBoard/IGCAPT_XMLConverter
          - IdahoLabCuttingBoard/inl-azure-devops-tasks
          - IdahoLabCuttingBoard/LEAF
          - IdahoLabCuttingBoard/LinuxSA
          - IdahoLabCuttingBoard/LRS_SORT
          - IdahoLabCuttingBoard/PolyPole
          - IdahoLabCuttingBoard/PowDDeR
          - IdahoLabCuttingBoard/WEST
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
          databranch: main

  update-stats-external:
    if: always()
    needs: update-stats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepoExt:
          - cisagov/ICSNPP
          - cisagov/icsnpp-bacnet
          - cisagov/icsnpp-bsap
          - cisagov/icsnpp-dnp3
          - cisagov/icsnpp-enip
          - cisagov/icsnpp-ethercat
          - cisagov/icsnpp-genisys
          - cisagov/icsnpp-modbus
          - cisagov/icsnpp-opcua-binary
          - cisagov/icsnpp-s7comm
          - cisagov/Malcolm
          - cisagov/network-architecture-verification-and-validation
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs-ext
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ matrix.statsRepoExt }}
          ghtoken: ${{ secrets.GHRS_EXT_GITHUB_API_TOKEN }}
          databranch: main
